; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
lib_deps =
    powerbroker2/SerialTransfer
    ivanseidel/LinkedList
    paulstoffregen/Time
    LSatan/SmartRC-CC1101-Driver-Lib
    wollewald/ICM20948_WE
    BMP388_DEV
    mikalhart/TinyGPSPlus
   # adafruit/Adafruit_Sensor
   # adafruit/Adafruit_ICM20948
   # adafruit/Adafruit_BMP3XX

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug  

[env:fli3dv2_esp32]
board = mhetesp32minikit
build_src_filter = +<../projects/fli3dv2_esp32/*>
build_flags = 
    -DPLATFORM_ESP32
#upload_port = 192.168.27.162
#upload_protocol = espota
#upload_flags = 
#    -p 3232
#    --auth=fli3d

[env:fli3dv2_esp32cam]
board = esp32cam
build_src_filter = +<../projects/fli3dv2_esp32cam/*>
build_flags = 
    -DPLATFORM_ESP32CAM 
    -DBOARD_HAS_PSRAM 
    -mfix-esp32-psram-cache-issue
board_build.partitions = huge_app.csv

[env:fli3dv2_gndctrl]
board = mhetesp32minikit
build_src_filter = +<../projects/fli3dv2_gndctrl/*>
build_flags = 
    -DPLATFORM_GNDCTRL
upload_port = 192.168.27.162
upload_protocol = espota
upload_flags = 
    -p 3232
    --auth=fli3d

[env:test]
board = mhetesp32minikit
build_src_filter = +<../projects/test/*>
build_flags = 
    -DPLATFORM_TEST

[platformio]
#default_envs = fli3dv2_gndctrl
#default_envs = fli3dv2_esp32
default_envs = fli3dv2_esp32cam
#default_envs = test
#default_envs = test_ota
#default_envs = test_radio
