; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
lib_deps =
    powerbroker2/SerialTransfer
    ivanseidel/LinkedList
    paulstoffregen/Time

[env:fli3dv2_esp32]
board = esp32dev
build_src_filter = +<../projects/fli3dv2_esp32/*>
build_flags = -DPLATFORM_ESP32

[env:fli3dv2_esp32cam]
board = esp32cam
build_src_filter = +<../projects/fli3dv2_esp32cam/*>
build_flags = -DPLATFORM_ESP32CAM -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue
board_build.partitions = huge_app.csv

[env:fli3dv2_gndctrl]
board = esp32dev
build_src_filter = +<../projects/fli3dv2_gndctrl/*>
build_flags = -DPLATFORM_GNDCTRL

[platformio]
default_envs = fli3dv2_gndctrl
#default_envs = fli3dv2_esp32